### ISSUE TITLE
Skip process.exit(1) in Browser mode

### ISSUE THREAD

**Issue by Kim-Andersen** [af/envalid#101]
First of all, thank you for a handy and well crafted tool.

Small issue: the `process.exit(1)` call throws in a browser because the **exit** method is not defined.
Maybe skip that call when in browser mode?

**Comment by af** [comment]
Yeah, browser usage was never really intended for this library initially, which is why node apis like `process.exit()` are used in various places. I'm thinking we could add a new option like `onExit`, which would allow the consuming code to override this default exit behavior. Would that work for your case?

**Comment by Kim-Andersen** [comment]
> Yeah, browser usage was never really intended for this library initially, which is why node apis like `process.exit()` are used in various places. I'm thinking we could add a new option like `onExit`, which would allow the consuming code to override this default exit behavior. Would that work for your case?

Yes, `onExit` would do the job.

**Comment by SimenB** [comment]
Is it not enough to just provide a custom `reporter`? https://github.com/af/envalid/blob/ad2f612ddef8b4a07d6b6d553f33aad21cbfb849/README.md#error-reporting

**Comment by af** [comment]
Ah! Thank you @SimenB, I forgot `process.exit()` is only used in the reporter. That's definitely the 
way to go here, so closing this out.

**Comment by kachkaev** [comment]
It'd be useful to split a [defaultReporter](https://github.com/af/envalid/blob/6f44bb33084bdbc3913bffbb12c4c3293cb2e173/src/reporter.js) function into two: one would dump errors into an output string and another one will run `console.error` and `process.exit`.

I’ve got at least two projects where I'd be interested in importing the dump function. In those, I prefer throwing instead of exiting inside the reporter, because having a valid env is an optional thing.

@af will you be happy to accept a PR that extracts `dumpErrors` from `defaultReporter` and exports the new function as `envalid.dumpErrors`? Happy to work on it. I know I can just copy-paste the code and format errors as I want, but I like you that's done in the libarary, so keen to keep my output's style in sync with the original.

----

Here is my workaround for now:

```js
const defaultReporter = require("envalid/src/reporter");

const customReporter = (opts) => {
  const originalConsoleError = console.error;
  const originalProcessExit = process.exit;

  let errorOutput = "";
  console.error = (output) => {
    errorOutput += output;
  };
  process.exit = () => undefined as never;

  defaultReporter(opts);

  process.exit = originalProcessExit;
  console.error = originalConsoleError;

  if (errorOutput) {
    throw new Error("Environment variables are not valid\n\n" + errorOutput);
  }
};
```

Instead, I'd be keen to write:

```js
const { dumpErrors } = require "envalid";

const customReporter = (opts) => {
  const output = dumpErrors(opts)
  if (output) {
    throw new Error("Environment variables are not valid\n\n" + output);
  }
};
```
