### ISSUE TITLE
Help with Next.js 

### ISSUE THREAD

**Issue by nenadfilipovic** [af/envalid#168]
Any advice how to set up this lib with Next.js, I have standard setup and Next is throwing me error every time.

```
================================
 NEXT_PUBLIC_BASE_URL: undefined
 Missing environment variables:

 Exiting with error code 1
================================
```

`TypeError: Environment validation failed`

Here is env var.
```
NEXT_PUBLIC_BASE_URL="http://localhost:3000"
```

I have tried to pass env vars thru Next `serverRuntimeConfig` and `publicRuntimeConfig` but it does not work. Seems like my variable is not set on runtime.

Here is sandbox with example: https://codesandbox.io/s/cold-wildflower-wwd0w (`npm run dev`)

**Comment by nenadfilipovic** [comment]
With added env variables like this https://medium.com/courtly-intrepid/environmental-variables-in-next-js-with-dotenv-599c5bbfdf74, I have access to env vars in both server and client and it still throws error. Is there any nextjs example available?

**Comment by nenadfilipovic** [comment]
Nah, I abandoned this lib.

**Comment by af** [comment]
@nenadfilipovic Any chance you could restore the codesandbox with the repro case?

**Comment by stefan-girlich** [comment]
On using `envalid` with next.js:
- server-side usage works as expected as next.js runs in a standard Node.js runtime with full access to `process.env` (see `cleanEnv(process.env, /*...*/)`
- client-side/browser usage with next.js seems impossible since `process.env` is not a standard object and only explicitly referenced variables are actually available in the brwoser ([source](https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables))
