### ISSUE TITLE
Generating example .env file

### ISSUE THREAD

**Issue by alekbarszczewski** [af/envalid#72]
It would be cool if it was possible to generate example .env file from envalid configuration. Would be helpful when someone installs application for the first time and wants to generate .env file (to run app locally).
It could also assign example values to env vars (if they are defined in envalid config).

**Comment by af** [comment]
I like this suggestion! It's not something that I need personally, but I'd welcome a PR for it. Not sure how it would handle required values that don't have defaults though. Maybe `REQUIRED_VAR=todo`?

I'm closing this issue since I like to keep open issues to actionable items and near-term TODOs, but happy to continue discussion and consider PRs.

**Comment by SimenB** [comment]
I would also love to see this. Seems very useful!
