### ISSUE TITLE
Asynchronous validation

### ISSUE THREAD

**Issue by nicwaller** [af/envalid#8]
It would be nice to support asynchronous validation via callbacks. This would unlock some use cases that aren't possible with synchronous validation. Examples:

* Validate a hostname using a DNS lookup. This is a much stronger validation than can be provided with just regular expressions.
* Test network connectivity to supporting services in the launch phase. A process could choose to exit if some dependencies are unavailable. Then the retry logic can be taken care of by a supervisor process like runit or upstart.

I have some code that's already doing this, but I'm not sure if this matches your goals for the project. Maybe it would work better as a separate module. Let me know what you think!

**Comment by af** [comment]
Interesting idea, could be useful for sure. I don't want to commit to supporting this since I'm not sure if the extra complexity would be worthwhile. I'd say try and do it with a separate module first (I'm happy to link from the readme). Maybe envalid needs to provide extra hooks to make this possible.

If doing it in another module doesn't work, I'd be happy to look at a PR. Thanks for all the commits and suggestions so far!

**Comment by nicwaller** [comment]
Okay, I'll consider starting a new module for this. Thanks for the input!
